# Generated by Django 2.2.1 on 2019-05-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=32768, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='brunch',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст'),
        ),
    ]
